### ISSUE TITLE
macOS 10.13 + OpenJDK 11 -- HTTP 500 error in localhost:8080

### ISSUE THREAD

**Issue by robolmos** [mkalus/segrada#50]
The error looks to be the same as #41 -- I'm using the built version available from the website: https://segrada.org/fileadmin/downloads/Segrada.tar.gz -- not sure which version this is.

Java/openjdk installed via brew: brew cask install java

[Segrada]$ java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

Fresh install, ran via ./start_mac.command -- viewing via localhost:8080

The first viewing gave me a broken page, like HTML was there but none of the styles were being loaded. Errors like this in console:

68863 [qtp1509060235-45] WARN  org.eclipse.jetty.server.HttpChannel  - /css/vis.css
javax.servlet.ServletException: java.lang.ClassCastException: class java.util.regex.Matcher$ImmutableMatchResult cannot be cast to class java.util.regex.Matcher (java.util.regex.Matcher$ImmutableMatchResult and java.util.regex.Matcher are in module java.base of loader 'bootstrap')

Refreshing the page would then cause a 500 error with this on the page:

Caused by:
java.lang.ClassCastException: class java.util.regex.Matcher$ImmutableMatchResult cannot be cast to class java.util.regex.Matcher (java.util.regex.Matcher$ImmutableMatchResult and java.util.regex.Matcher are in module java.base of loader 'bootstrap')
	at org.segrada.servlet.SegradaSimplePageCachingFilter.calculateKey(SegradaSimplePageCachingFilter.java:123)
	at net.sf.ehcache.constructs.web.filter.CachingFilter.buildPageInfo(CachingFilter.java:238)
	at net.sf.ehcache.constructs.web.filter.CachingFilter.doFilter(CachingFilter.java:216)
	at org.segrada.servlet.SegradaSimplePageCachingFilter.doFilter(SegradaSimplePageCachingFilter.java:95)
	at net.sf.ehcache.constructs.web.filter.Filter.doFilter(Filter.java:86)
	at org.segrada.servlet.CSRFFilter.doFilter(CSRFFilter.java:68)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:530)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by mkalus** [comment]
Seems to be a problem with caching and Java 11. Will have to look into this.

**Comment by mkalus** [comment]
Hello robolmos,

I have checked Java 11 and there seem to be numerous incompatibilities which I can not fix at this time.

Main reason, as far as I see is that Google's guice servlet package throws errors in Java 11. If anyone wants to fix this, I am happy to get help on that matter.

**Comment by mkalus** [comment]
You can still try with Java 8. In homebrew you can use brew cask install java8.

**Comment by mkalus** [comment]
Closing this - added note on README a while ago.
